### ISSUE TITLE
Test get/set Type and get/set Count

### ISSUE THREAD

**Issue by brodzik** [amasiukevich/TINs#24]
https://github.com/amasiukevich/TINs/blob/46fcfb2b70b0b8c36d4f8e3a8997fff4439a71a1/src/common/aaa.cpp#L3-L42

**Comment by jsokolowska** [comment]
Some tests added in #32 
https://github.com/amasiukevich/TINs/blob/313d284c30b9c6f5ccc4abcc5f837c94c3557357/test/test1.cpp#L13
